name: odoo_sso
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.2.2
  odoo_rpc: ^0.5.7
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^4.9.0
  djangoflow_odoo_auth: ^0.1.0+1
  djangoflow_odoo_oauth: ^0.0.2+1
  flutter_bloc: ^8.1.6
  djangoflow_app: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
